'use client'

import { useMemo, useState } from 'react'
import {
  Activity, BarChart3, BookOpen, CalendarDays, Check, ChevronDown, CircleHelp,
  FileText, Filter, LayoutDashboard, Menu, MoreHorizontal, Plus, Search,
  Settings2, ShieldCheck, Sparkles, Target, TrendingUp, WalletCards, X,
} from 'lucide-react'

type Trade = { id: number; symbol: string; side: 'Long' | 'Short'; setup: string; date: string; pnl: number; r: number }
const navItems = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Trade log', icon: Activity },
  { label: 'Calendar', icon: CalendarDays }, { label: 'Analytics', icon: BarChart3 },
  { label: 'Strategies', icon: Target }, { label: 'Journal', icon: BookOpen },
]
const workspaceItems = [
  { label: 'Playbook', icon: FileText }, { label: 'Accounts', icon: WalletCards },
  { label: 'Prop firms', icon: ShieldCheck }, { label: 'EdgeCoach', icon: Sparkles, accent: true },
  { label: 'Reports', icon: FileText },
]
const initialTrades: Trade[] = []

const pageCopy: Record<string, { eyebrow: string; title: string; description: string }> = {
  Overview: { eyebrow: 'Live overview', title: 'Your trading edge', description: "A clear view of what's working and where to improve." },
  'Trade log': { eyebrow: 'Execution journal', title: 'Trade log', description: 'Review, filter, and annotate every execution.' },
  Calendar: { eyebrow: 'Trading schedule', title: 'Calendar', description: 'Plan your sessions and review daily performance.' },
  Analytics: { eyebrow: 'Performance lab', title: 'Analytics', description: 'Turn your trade history into decisions you can repeat.' },
  Strategies: { eyebrow: 'Your edge library', title: 'Strategies', description: 'Define the setups you trade and measure their outcomes.' },
  Journal: { eyebrow: 'Session notes', title: 'Journal', description: 'Capture context before it disappears.' },
  Playbook: { eyebrow: 'Operating system', title: 'Playbook', description: 'Keep your rules, checklists, and best practices close.' },
  Accounts: { eyebrow: 'Capital overview', title: 'Accounts', description: 'Organize your brokers, evaluations, and buying power.' },
  'Prop firms': { eyebrow: 'Evaluation tracker', title: 'Prop firms', description: 'Monitor rules and progress across your evaluations.' },
  EdgeCoach: { eyebrow: 'Personal coach', title: 'EdgeCoach', description: 'Use your journal and metrics to build better habits.' },
  Reports: { eyebrow: 'Export center', title: 'Reports', description: 'Create clean summaries for review, sharing, or tax time.' },
  Settings: { eyebrow: 'Workspace controls', title: 'Settings', description: 'Configure your workspace and trading preferences.' },
  'Help center': { eyebrow: 'Support', title: 'Help center', description: 'Find answers and learn how to get more from EdgeLog.' },
}

function Logo() { return <div className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-cyan-400 text-[15px] font-black text-slate-950 shadow-[0_0_22px_rgba(34,211,238,0.28)]">E</div><span className="text-[16px] font-semibold tracking-[-0.03em] text-white">Edge<span className="text-cyan-300">Log</span></span></div> }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-white/[0.07] bg-[#0d141e] p-4 sm:p-5 ${className}`}>{children}</section> }
function EmptyState({ title, text, action, onAction }: { title: string; text: string; action?: string; onAction?: () => void }) { return <div className="flex min-h-[210px] flex-col items-center justify-center rounded-xl border border-dashed border-white/[0.1] bg-white/[0.015] px-6 text-center"><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-300"><Sparkles size={18} /></div><p className="text-[13px] font-medium text-slate-300">{title}</p><p className="mt-1 max-w-sm text-[11px] leading-5 text-slate-600">{text}</p>{action && <button onClick={onAction} className="mt-4 rounded-lg bg-cyan-300 px-3 py-2 text-[11px] font-bold text-slate-950 hover:bg-cyan-200">{action}</button>}</div> }
function Metric({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) { return <Card className="p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[11px] text-slate-500">{label}</span><span className="text-cyan-300">{icon}</span></div><p className="text-[20px] font-semibold tracking-[-0.04em] text-white">{value}</p><p className="mt-2 text-[10px] text-slate-600">{detail}</p></Card> }

export default function EdgeLogDashboard({ user }: { user: { name: string; email: string } }) {
  const [active, setActive] = useState('Overview'); const [mobileNav, setMobileNav] = useState(false); const [addOpen, setAddOpen] = useState(false)
  const [trades, setTrades] = useState<Trade[]>(initialTrades); const [search, setSearch] = useState(''); const [symbol, setSymbol] = useState(''); const [side, setSide] = useState<'Long' | 'Short'>('Long'); const [pnl, setPnl] = useState('')
  const copy = pageCopy[active] ?? pageCopy.Overview
  const filteredTrades = useMemo(() => trades.filter(t => `${t.symbol} ${t.setup}`.toLowerCase().includes(search.toLowerCase())), [trades, search])
  const go = (label: string) => { setActive(label); setMobileNav(false) }
  const addTrade = () => { if (!symbol.trim()) return; setTrades(current => [{ id: Date.now(), symbol: symbol.toUpperCase(), side, setup: 'Manual entry', date: 'Today', pnl: Number(pnl) || 0, r: 0 }, ...current]); setSymbol(''); setPnl(''); setAddOpen(false) }
  return <div className="min-h-screen bg-[#080c12] text-slate-200 selection:bg-cyan-300/30">
    <aside className={`${mobileNav ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 flex w-[246px] flex-col border-r border-white/[0.07] bg-[#0b1018] px-4 py-5 transition-transform lg:translate-x-0`}>
      <div className="mb-8 flex items-center justify-between px-2"><Logo /><button onClick={() => setMobileNav(false)} className="text-slate-500 lg:hidden" aria-label="Close menu"><X size={18} /></button></div>
      <nav className="space-y-1">{navItems.map(item => <NavButton key={item.label} {...item} active={active} onClick={go} />)}</nav>
      <p className="mb-2 mt-8 px-3 text-[10px] font-semibold uppercase tracking-[0.17em] text-slate-600">Workspace</p><nav className="space-y-1">{workspaceItems.map(item => <NavButton key={item.label} {...item} active={active} onClick={go} />)}</nav>
      <div className="mt-auto space-y-1 border-t border-white/[0.07] pt-4"><NavButton label="Settings" icon={Settings2} active={active} onClick={go} /><NavButton label="Help center" icon={CircleHelp} active={active} onClick={go} /><div className="mt-3 flex items-center gap-2.5 rounded-xl bg-white/[0.04] p-2"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-br from-violet-400 to-cyan-300 text-[10px] font-bold text-slate-950">{user.name.slice(0, 2).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-[11px] font-medium text-slate-200">{user.name}</p><p className="text-[10px] text-slate-600">Pro plan</p></div><MoreHorizontal size={15} className="ml-auto text-slate-600" /></div></div>
    </aside>
    <div className="lg:pl-[246px]"><header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-white/[0.07] bg-[#080c12]/90 px-5 backdrop-blur-xl lg:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileNav(true)} className="text-slate-400 lg:hidden" aria-label="Open menu"><Menu size={20} /></button><div><p className="text-[11px] text-slate-500">Tuesday, June 30, 2026</p><h1 className="text-[16px] font-semibold tracking-[-0.02em] text-white">Good morning, {user.name}</h1></div></div><div className="flex items-center gap-2.5"><button onClick={() => setAddOpen(true)} className="flex items-center gap-2 rounded-lg bg-cyan-300 px-3 py-2 text-[11px] font-bold text-slate-950 shadow-[0_0_18px_rgba(34,211,238,0.18)] hover:bg-cyan-200"><Plus size={15} strokeWidth={2.5} /> Add trade</button></div></header>
      <main className="mx-auto max-w-[1500px] px-5 py-7 lg:px-8"><div className="mb-7 flex items-end justify-between"><div><div className="mb-2 flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]" /><span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">{copy.eyebrow}</span></div><h2 className="text-[26px] font-semibold tracking-[-0.04em] text-white">{copy.title}</h2><p className="mt-1 text-[12px] text-slate-500">{copy.description}</p></div></div>
        {active === 'Overview' && <Overview trades={trades} onAdd={() => setAddOpen(true)} onTradeLog={() => go('Trade log')} />}
        {active === 'Trade log' && <TradeLog trades={filteredTrades} search={search} setSearch={setSearch} onAdd={() => setAddOpen(true)} />}
        {active === 'Calendar' && <Calendar trades={trades} />}
        {active === 'Analytics' && <Analytics trades={trades} />}
        {['Strategies', 'Journal', 'Playbook', 'Accounts', 'Prop firms', 'EdgeCoach', 'Reports', 'Settings', 'Help center'].includes(active) && <WorkspacePage active={active} onAdd={() => setAddOpen(true)} />}
      </main></div>
    {addOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-[440px] rounded-2xl border border-white/10 bg-[#111923] p-5 shadow-2xl"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-[16px] font-semibold text-white">Add a trade</h2><p className="mt-1 text-[11px] text-slate-500">Log an execution while it's fresh.</p></div><button onClick={() => setAddOpen(false)} aria-label="Close" className="text-slate-500 hover:text-white"><X size={18} /></button></div><div className="grid grid-cols-2 gap-3"><label className="col-span-2 space-y-1.5"><span className="text-[10px] text-slate-500">Symbol</span><input autoFocus value={symbol} onChange={e => setSymbol(e.target.value)} placeholder="NQ" className="w-full rounded-lg border border-white/[0.09] bg-white/[0.03] px-3 py-2.5 text-[12px] text-white outline-none focus:border-cyan-300/60" /></label><label className="space-y-1.5"><span className="text-[10px] text-slate-500">Net P&L</span><input value={pnl} onChange={e => setPnl(e.target.value)} placeholder="0.00" inputMode="decimal" className="w-full rounded-lg border border-white/[0.09] bg-white/[0.03] px-3 py-2.5 text-[12px] text-white outline-none focus:border-cyan-300/60" /></label><div className="space-y-1.5"><span className="text-[10px] text-slate-500">Direction</span><div className="grid grid-cols-2 gap-2"><button onClick={() => setSide('Long')} className={`rounded-lg border py-2.5 text-[11px] ${side === 'Long' ? 'border-emerald-400/40 bg-emerald-400/10 text-emerald-300' : 'border-white/[0.09] text-slate-500'}`}>Long</button><button onClick={() => setSide('Short')} className={`rounded-lg border py-2.5 text-[11px] ${side === 'Short' ? 'border-rose-400/40 bg-rose-400/10 text-rose-300' : 'border-white/[0.09] text-slate-500'}`}>Short</button></div></div></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setAddOpen(false)} className="rounded-lg px-3 py-2 text-[11px] text-slate-400 hover:text-white">Cancel</button><button onClick={addTrade} className="rounded-lg bg-cyan-300 px-4 py-2 text-[11px] font-bold text-slate-950 hover:bg-cyan-200">Save trade</button></div></div></div>}
  </div>
}

function NavButton({ label, icon: Icon, active, onClick, accent }: { label: string; icon: React.ElementType; active: string; onClick: (label: string) => void; accent?: boolean }) { return <button onClick={() => onClick(label)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[12px] font-medium transition ${active === label ? 'bg-white/[0.08] text-white' : 'text-slate-500 hover:bg-white/[0.04] hover:text-slate-300'}`}><Icon size={16} strokeWidth={1.8} /><span className={accent ? 'text-cyan-300' : ''}>{label}</span>{accent && <span className="ml-auto rounded bg-cyan-400/10 px-1.5 py-0.5 text-[9px] text-cyan-300">AI</span>}</button> }
function Overview({ trades, onAdd, onTradeLog }: { trades: Trade[]; onAdd: () => void; onTradeLog: () => void }) { const pnl = trades.reduce((sum, t) => sum + t.pnl, 0); return <><section className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Net P&L" value={`$${pnl.toFixed(2)}`} detail={trades.length ? `${trades.length} trades logged` : 'No trades yet'} icon={<TrendingUp size={15} />} /><Metric label="Win rate" value={trades.length ? `${Math.round(trades.filter(t => t.pnl > 0).length / trades.length * 100)}%` : '—'} detail="Across logged trades" icon={<Target size={15} />} /><Metric label="Profit factor" value="—" detail="Needs more data" icon={<Activity size={15} />} /><Metric label="Max drawdown" value="$0.00" detail="No losses recorded" icon={<BarChart3 size={15} />} /></section><div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,0.85fr)]"><Card><div className="mb-5"><h3 className="text-[13px] font-semibold text-white">Equity curve</h3><p className="mt-1 text-[11px] text-slate-500">Cumulative performance across all accounts</p></div><EmptyState title="Your equity curve starts here" text="Log your first trade to see performance build over time." action="Add first trade" onAction={onAdd} /></Card><Card><h3 className="text-[13px] font-semibold text-white">Performance pulse</h3><p className="mt-1 text-[11px] text-slate-500">Your most important signals</p><div className="mt-5"><EmptyState title="No signal yet" text="Once you have a few trades, EdgeLog will surface patterns." /></div></Card></div><Card className="mt-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-[13px] font-semibold text-white">Recent trades</h3><p className="mt-1 text-[11px] text-slate-500">Your latest executions</p></div><button onClick={onTradeLog} className="text-[11px] font-medium text-cyan-300">View trade log →</button></div>{trades.length ? <TradeTable trades={trades.slice(0, 5)} /> : <EmptyState title="No trades logged yet" text="Add your first trade to start tracking performance." action="Add trade" onAction={onAdd} />}</Card></> }
function TradeLog({ trades, search, setSearch, onAdd }: { trades: Trade[]; search: string; setSearch: (value: string) => void; onAdd: () => void }) { return <Card><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-[13px] font-semibold text-white">All executions</h3><p className="mt-1 text-[11px] text-slate-500">{trades.length} matching trades</p></div><button onClick={onAdd} className="flex items-center gap-2 rounded-lg bg-cyan-300 px-3 py-2 text-[11px] font-bold text-slate-950"><Plus size={14} /> Add trade</button></div><div className="mb-4 flex items-center gap-2 rounded-lg border border-white/[0.07] bg-white/[0.02] px-3 py-2"><Search size={14} className="text-slate-600" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search symbol or setup" className="w-full bg-transparent text-[11px] text-slate-200 outline-none placeholder:text-slate-600" /><Filter size={13} className="text-slate-600" /></div>{trades.length ? <TradeTable trades={trades} /> : <EmptyState title="Your trade log is empty" text="Capture the next execution and it will show up here." action="Log a trade" onAction={onAdd} />}</Card> }
function TradeTable({ trades }: { trades: Trade[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead><tr className="border-b border-white/[0.07] text-[10px] uppercase tracking-[0.12em] text-slate-600"><th className="pb-2 font-medium">Trade</th><th className="pb-2 font-medium">Setup</th><th className="pb-2 font-medium">Date</th><th className="pb-2 font-medium">R</th><th className="pb-2 text-right font-medium">Net P&L</th></tr></thead><tbody>{trades.map(t => <tr key={t.id} className="border-b border-white/[0.045] text-[11px] last:border-0"><td className="py-3"><span className="font-semibold text-white">{t.symbol}</span><span className={`ml-2 text-[10px] ${t.side === 'Long' ? 'text-emerald-300' : 'text-rose-300'}`}>{t.side}</span></td><td className="py-3 text-slate-400">{t.setup}</td><td className="py-3 text-slate-500">{t.date}</td><td className="py-3 text-slate-500">{t.r.toFixed(1)}R</td><td className={`py-3 text-right font-semibold ${t.pnl >= 0 ? 'text-emerald-300' : 'text-rose-300'}`}>{t.pnl >= 0 ? '+' : ''}${t.pnl.toFixed(2)}</td></tr>)}</tbody></table></div> }
function Calendar({ trades }: { trades: Trade[] }) { return <div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Card><div className="mb-5 flex items-center justify-between"><div><h3 className="text-[13px] font-semibold text-white">June 2026</h3><p className="mt-1 text-[11px] text-slate-500">Your trading activity at a glance</p></div><ChevronDown size={15} className="text-slate-500" /></div><div className="grid grid-cols-7 gap-1 text-center text-[10px] text-slate-600">{['M','T','W','T','F','S','S'].map((d, i) => <span key={`${d}-${i}`} className="pb-2">{d}</span>)}{Array.from({ length: 30 }, (_, i) => <div key={i} className={`flex h-10 items-center justify-center rounded-lg ${i === 29 ? 'border border-cyan-300/40 bg-cyan-300/10 text-cyan-200' : 'bg-white/[0.02] text-slate-500'}`}>{i + 1}</div>)}</div></Card><Card><h3 className="text-[13px] font-semibold text-white">Day summary</h3><p className="mt-1 text-[11px] text-slate-500">Tuesday, June 30</p><div className="mt-6"><EmptyState title={trades.length ? `${trades.length} trades logged` : 'No session logged'} text="Select a day to review trades, notes, and screenshots." /></div></Card></div> }
function Analytics({ trades }: { trades: Trade[] }) { return <><section className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Sample size" value={`${trades.length}`} detail="Total logged trades" icon={<Activity size={15} />} /><Metric label="Average winner" value="—" detail="No winning trades" icon={<TrendingUp size={15} />} /><Metric label="Average loser" value="—" detail="No losing trades" icon={<BarChart3 size={15} />} /><Metric label="Best setup" value="—" detail="Needs trade data" icon={<Target size={15} />} /></section><div className="grid gap-5 xl:grid-cols-2"><Card><h3 className="text-[13px] font-semibold text-white">Performance by setup</h3><p className="mt-1 text-[11px] text-slate-500">Compare the ideas behind your trades</p><div className="mt-5"><EmptyState title="Not enough data" text="Log at least a few trades to unlock setup-level analysis." /></div></Card><Card><h3 className="text-[13px] font-semibold text-white">Behavior patterns</h3><p className="mt-1 text-[11px] text-slate-500">Find the habits behind your results</p><div className="mt-5"><EmptyState title="Patterns will appear here" text="EdgeLog needs trading history before it can identify repeatable behavior." /></div></Card></div></> }
function WorkspacePage({ active, onAdd }: { active: string; onAdd: () => void }) { const data: Record<string, [string, string]> = { Strategies: ['Create your first strategy', 'Define entry, risk, and exit rules so every setup is measurable.'], Journal: ['Start a trading journal', 'Write a quick pre-market plan or post-session review.'], Playbook: ['Build your playbook', 'Turn your best processes into checklists you can follow.'], Accounts: ['Connect your first account', 'Keep balances, risk limits, and performance organized.'], 'Prop firms': ['Track an evaluation', 'Set targets and risk rules for every prop firm challenge.'], EdgeCoach: ['EdgeCoach is ready', 'Log trades and journal sessions to unlock personalized coaching.'], Reports: ['Create your first report', 'Export a clean performance summary for your next review.'], Settings: ['Your workspace is yours', 'Preferences and notification controls will live here.'], 'Help center': ['How can we help?', 'Browse guides or reach out when you need a hand.'] }; const [title, text] = data[active]; return <Card><div className="max-w-xl"><h3 className="text-[18px] font-semibold text-white">{title}</h3><p className="mt-2 text-[12px] leading-6 text-slate-500">{text}</p><button onClick={onAdd} className="mt-6 flex items-center gap-2 rounded-lg bg-cyan-300 px-3 py-2 text-[11px] font-bold text-slate-950"><Check size={14} /> Get started</button></div></Card> }
